name: flutter_built_redux_hooks
description: Adds flutter hooks for built redux
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_redux: ^7.5.2
  flutter_hooks: ^0.2.1
  provider: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  built_value_generator: ^6.0.0
  built_value_test: ^6.3.0
